### ISSUE TITLE
 Could not find an available JavaScript runtime.

### ISSUE THREAD

**Issue by dima734** [doloopwhile/Python-CoffeeScript#23]
>>> import coffeescript
>>> print(coffeescript.compile('add = (a, b) -> a + b'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/coffeescript/__init__.py", line 105, in compile
    return _default_compiler().compile(script, bare=bare)
  File "/usr/local/lib/python3.5/dist-packages/coffeescript/__init__.py", line 138, in _default_compiler
    get_runtime()
  File "/usr/local/lib/python3.5/dist-packages/coffeescript/__init__.py", line 127, in get_runtime
    return execjs.get()
  File "/usr/local/lib/python3.5/dist-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/usr/local/lib/python3.5/dist-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.

**Comment by doloopwhile** [comment]
I think you need to install a JS engine supported by PyExecJS.

https://github.com/doloopwhile/PyExecJS
